import * as esbuild from "esbuild";
import { copyFileSync, mkdirSync } from "node:fs";
import { builtinModules } from "node:module";
import process from "node:process";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const externals = [
  "obsidian",
  "electron",
  "@codemirror/autocomplete",
  "@codemirror/collab",
  "@codemirror/commands",
  "@codemirror/language",
  "@codemirror/lint",
  "@codemirror/search",
  "@codemirror/state",
  "@codemirror/view",
  "@lezer/common",
  "@lezer/highlight",
  "@lezer/lr",
  ...builtinModules.flatMap((m) =>
    m.startsWith("node:") ? [m] : [m, `node:${m}`]
  ),
];

const contextParams: esbuild.BuildOptions = {
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: externals,
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "output/main.js",
};

// The plugin install folder needs the bundle plus static files together,
// so copy them next to the bundle on every build.
function copyStaticFiles() {
  mkdirSync("output", { recursive: true });
  copyFileSync("manifest.json", "output/manifest.json");
  copyFileSync("src/styles.css", "output/styles.css");
}

if (prod) {
  await esbuild.build(contextParams);
  copyStaticFiles();
  esbuild.stop();
} else {
  const ctx = await esbuild.context(contextParams);
  await ctx.watch();
  copyStaticFiles();
}
